export const ACCESS_DECISION_STALE_TIME = 30_000
export const ACCESS_DECISION_GC_TIME = 5 * 60 * 1000
export const ACCESS_DECISION_RETRY = 1
export const ACCESS_DECISION_REFETCH_ON_WINDOW_FOCUS = true
